Simulation of multiple random walks

# Why don't just use randint(-1,1)?
Because that will involve number 0

In [2]:
import numpy as np

In [3]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0,2, size=(nwalks, nsteps))
steps = np.where(draws > 0,1,-1)
walks = steps.cumsum(1)
walks

array([[  1,   0,  -1, ..., -12, -13, -12],
       [  1,   2,   3, ...,  34,  35,  36],
       [ -1,   0,   1, ...,  -2,  -3,  -4],
       ...,
       [  1,   0,   1, ..., -14, -15, -14],
       [ -1,  -2,  -3, ...,  46,  45,  46],
       [  1,   2,   1, ...,   8,   7,   8]], dtype=int32)

In [7]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30.sum()

3385

# Why would it use X.argmax()?
Q: What's the meaning of this usage?
Answer:
# What's the difference between `walks[hits30]` and `np.abs(walks[hits30]) >= 30`
Q: `hits30` already defines that all values' abs are >= 30, why would it use another `np.abs` to check if >=30?
Answer:

In [16]:
# Checking the two results
print(np.abs(walks))
print('----------------')
print(np.abs(walks[hits30]))

[[ 1  0  1 ... 12 13 12]
 [ 1  2  3 ... 34 35 36]
 [ 1  0  1 ...  2  3  4]
 ...
 [ 1  0  1 ... 14 15 14]
 [ 1  2  3 ... 46 45 46]
 [ 1  2  1 ...  8  7  8]]
----------------
[[ 1  0  1 ... 12 13 12]
 [ 1  2  3 ... 34 35 36]
 [ 1  2  3 ... 34 33 34]
 ...
 [ 1  0  1 ... 62 61 62]
 [ 1  0  1 ... 14 15 14]
 [ 1  2  3 ... 46 45 46]]


In [14]:
crossing_times_2 = (walks[hits30]).argmax(1)
crossing_times_2.mean()

469.75834564254063

In [8]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

496.1326440177253